on: push
name: Lints and tests
jobs:
  lints-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install mypy ruff pytest .
      - run: ./build.py mypy
      - run: ./build.py lint
      - run: ./build.py fmt-ok
      - run: ./build.py test
