on: push
name: Lints and tests
jobs:
  lints-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m mypy src/
      - run: python3 -m ruff check src/
      - run: python3 -m ruff format --check src/
