on: push
name: Lints and tests
jobs:
  lints-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install '.[dev]'
      - run: ./mk.py mypy
      - run: ./mk.py lint
      - run: ./mk.py fmt-ok
      - run: ./mk.py test
